name: Fetch release ai-backend

on:
  push:
      branches:
        - main
  # schedule:
  #     - cron: '*/10 * * * *'
  # workflow_dispatch:  # ✅ ทำให้สามารถกดรันเองได้
        
permissions:
  contents: write
  packages: write
  id-token: write
  actions: write

env:
  REPO_AI_BACKEND: enersys/enersys-AI-backend
  ACCOUNT_SERVICE: account-api
  AGENT_SERVICE: agent-service
  CHANNEL_SERVICE: channel-service
  CHAT_SERVICE: chat-service
  LINECONNCET_SERVICE: lineconnect-service
  UPLOAD_SERVICE: upload-service
  WEB_SERVICE: web


jobs:
  fetch_release_json:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout current repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
  
        - name: Checkout release-dev repository (backend ai)
          uses: actions/checkout@v4
          with:
            repository: chanyapatEnersys/test-pipeline
            token: ${{ secrets.WORKFLOW_TOKEN }}
            path: test-pipeline
        
        - name: Remove .git from test-pipeline
          run: rm -rf test-pipeline/.git  

        - name: Checkout enersys-AI-website repository (web ui)
          uses: actions/checkout@v4
          with:
            repository: enersys/enersys-AI-website
            token: ${{ secrets.WORKFLOW_TOKEN }}
            path: enersys-AI-website
           
  
        - name: Copy release.json to this repo
          run: |
            mkdir -p release/account
            cp -r test-pipeline/apps/${{env.ACCOUNT_SERVICE}}/release.json release/account/release.json
            mkdir -p release/agent
            cp -r test-pipeline/apps/${{env.AGENT_SERVICE}}/release.json release/agent/release.json
            mkdir -p release/channel
            cp -r test-pipeline/apps/${{env.CHANNEL_SERVICE}}/release.json release/channel/release.json
            mkdir -p release/chat
            cp -r test-pipeline/apps/${{env.CHAT_SERVICE}}/release.json release/chat/release.json
            mkdir -p release/lineconnect
            cp -r test-pipeline/apps/${{env.LINECONNCET_SERVICE}}/release.json release/lineconnect/release.json
            mkdir -p release/upload
            cp -r test-pipeline/apps/${{env.UPLOAD_SERVICE}}/release.json release/upload/release.json
            mkdir -p release/ai-web
            cp -r enersys-AI-website/apps/${{env.WEB_SERVICE}}/release.json release/ai-web/release.json

        - name: Check if WORKFLOW_TOKEN is set
          run: |
            if [ -z "${{ secrets.WORKFLOW_TOKEN }}" ]; then
              echo "WORKFLOW_TOKEN is NOT set!"
              exit 1
            else
              echo "WORKFLOW_TOKEN is set!"
            fi     

        - name: Print WORKFLOW_TOKEN (masked)
          run: | 
            echo "WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}"
  
        - name: Commit & Push changes to current repository
          run: |
              git config --global user.email "github-actions[bot]@users.noreply.github.com"
              git config --global user.name "github-actions[bot]"
              git add release/
              git commit -m "Update release.json from test-pipeline" || echo "No changes to commit"
              git push origin main
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

